version: "3"

services:
  mc:
    image: itzg/minecraft-server
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
      TYPE: "QUILT"
      MODRINTH_PROJECTS: "https://modrinth.com/mod/fabric-api,https://modrinth.com/mod/fastback,https://modrinth.com/mod/multiworld,https://modrinth.com/mod/better-fabric-console,https://modrinth.com/mod/mods-command,https://modrinth.com/mod/suggestion-tweaker,https://modrinth.com/mod/styled-chat,https://modrinth.com/mod/styledplayerlist,https://modrinth.com/mod/afkdisplay,https://modrinth.com/mod/directionhud,https://modrinth.com/plugin/tabtps,https://modrinth.com/mod/debugify,https://modrinth.com/mod/thorium,https://modrinth.com/mod/clean-logs,https://modrinth.com/mod/lithium,https://modrinth.com/mod/starlight,https://modrinth.com/mod/ferrite-core,https://modrinth.com/mod/memoryleakfix,https://modrinth.com/mod/lazydfu,https://modrinth.com/mod/c2me-fabric,https://modrinth.com/mod/fastload,https://modrinth.com/plugin/chunky,https://modrinth.com/plugin/chunkyborder,https://modrinth.com/mod/carpet,https://modrinth.com/mod/carpet-extra,https://modrinth.com/mod/carpet-fixes,https://modrinth.com/mod/carpetgamerules,https://modrinth.com/mod/carpet-sky-additions,https://modrinth.com/mod/scarpet-graphics,https://modrinth.com/mod/slumber,https://modrinth.com/mod/essentialaddons,https://modrinth.com/datapack/multitool,https://modrinth.com/mod/starter-kit,https://modrinth.com/mod/cycle-paintings,https://modrinth.com/mod/inventory-essentials,https://modrinth.com/mod/compass-commands,https://modrinth.com/mod/skylands,https://modrinth.com/mod/highspeed-rail"
    volumes:
      - ./data:/data

    tty: true
    stdin_open: true
    restart: unless-stopped

volumes:
  data:
