version: "3"

services:
  mc:
    image: itzg/minecraft-server
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
      TYPE: "PAPER"
    volumes:
      - ./data:/data
      - ./plugins:/plugins
    tty: true
    stdin_open: true
    restart: unless-stopped

volumes:
  data:
  plugins: