version: "3"

services:
  mc:
    image: itzg/minecraft-server
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
      TYPE: "FABRIC"
      MODRINTH_PROJECTS: "https://modrinth.com/mod/better-fabric-console,https://modrinth.com/mod/player-roles,https://modrinth.com/mod/styled-chat,https://modrinth.com/mod/styledplayerlist,https://modrinth.com/mod/holograms,https://modrinth.com/mod/fabric-api,https://modrinth.com/plugin/tabtps,https://modrinth.com/mod/debugify,https://modrinth.com/mod/clean-logs,https://modrinth.com/mod/mod-loading-screen,https://modrinth.com/mod/lithium,https://modrinth.com/mod/starlight,https://modrinth.com/mod/ferrite-core,https://modrinth.com/mod/memoryleakfix,https://modrinth.com/mod/lazydfu,https://modrinth.com/mod/c2me-fabric,https://modrinth.com/mod/fastload,https://modrinth.com/plugin/chunky,https://modrinth.com/plugin/chunkyborder,https://modrinth.com/mod/carpet,https://modrinth.com/mod/carpet-extra,https://modrinth.com/mod/carpet-fixes,https://modrinth.com/mod/carpetgamerules,https://github.com/RubixDev/Rug,https://modrinth.com/mod/subtick,https://modrinth.com/mod/carpet-sky-additions,https://modrinth.com/mod/scarpet-graphics,https://modrinth.com/mod/essentialaddons,https://modrinth.com/plugin/huskhomes,https://modrinth.com/mod/discarpet,https://modrinth.com/mod/mcdiscordchat,https://modrinth.com/datapack/multitool,https://modrinth.com/mod/starter-kit,https://modrinth.com/mod/no-hostiles-around-campfire,https://modrinth.com/mod/inventory-essentials"
    volumes:
      - ./data:/data

    tty: true
    stdin_open: true
    restart: unless-stopped

volumes:
  data:
